### ISSUE TITLE
add gray to color palete

### ISSUE THREAD

**Issue by Maaaash32** [maghiel/skin.eminence.2#9]
I suggest you to change the colour palette. I did it manually for myself. I Would like the colour ff444444 for my turn off button so I changed 7th colour on the palette.

- First, I modified the file colors.xml in the directory [...]\skin.eminence.2\extras\colors with the notepad I changed the hexadecimal code and name of the 7th colour with ff444444
- Second, with PAINT i modified the colour and the name of the PNG file with the precedent 7th colour, in the colour I wanted ff444444.
- Third, I repeated the PAINT process with the PNG file of the 7th colour in the directory [...]\userdata\addon_data\skin.eminence.2\colors

![Maaaash32 Eminence2 home](https://github.com/user-attachments/assets/70175a08-d8cd-4f2f-994c-baadc86bcdf3)
![Maaaash32 colorsxml](https://github.com/user-attachments/assets/720a3e5a-233e-441b-a5f0-493c9e545b53)
![Maaaash32 Eminence2 color palette](https://github.com/user-attachments/assets/4d8c1769-440c-4ecf-986e-1b43e1614aa8)

**Comment by maghiel** [comment]
Thanks for the suggestion, I'll look into this! :) Doens't necessarily have to be the 7th color I'm going to replace; some people might use that color. 
Also, if you're interested, I can add your choice of colors as a color scheme. Although so many colors doens't really fit the minimalistic approach of Eminence I kinda like it, it's subtle.

**Comment by maghiel** [comment]
@Maaaash32 I'm simply adding the color to the color picker instead of replacing it. Once done you can scroll down in the color picker. I'll release it this evening. If you (or anyone else) want more colors added, just ask!
